version: '2'
services:
    setbuyapp-app:
        image: setbuyapp
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://setbuyapp-mysql:3306/setbuyapp?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=setbuyapp-elasticsearch:9300
        ports:
            - 8080:8080
    setbuyapp-mysql:
        extends:
            file: mysql.yml
            service: setbuyapp-mysql
    setbuyapp-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: setbuyapp-elasticsearch
